# Generated by Django 5.0.4 on 2024-04-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModel',
            new_name='CarsModel',
        ),
    ]
