# Generated by Django 5.0.4 on 2024-04-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_newcar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarsModel',
        ),
    ]
