# Generated by Django 5.0.4 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_delete_carsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcar',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newcar',
            name='v',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='newcar',
            table='cars',
        ),
    ]
