# Generated by Django 5.0.4 on 2024-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_newcar_price_newcar_v_alter_newcar_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='v',
            field=models.FloatField(default=0),
        ),
    ]
